[package]
name = "lc3_lsp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clippy = "0.0.302"
crossbeam = "0.8.4"
lsp-server = "0.7.9"
lsp-types = "0.97.0"
rustc-hash = "2.1.1"
serde = "1.0.228"
serde_json = "1.0.145"
toolchain = "0.1.0-alpha.1"
